// Change this so it's split into Northern Sask, Central Sask, and Southern Sask

export const saskatchewan = {
    "Regina": "64267202275fdf945fad68dd",
    "Saskatoon": "64267356275fdf945fad68eb",
    "Swift Current": "64267367275fdf945fad68ed",
    "Weyburn": "64267379275fdf945fad68f1",
    "Yorkton": "6426738a275fdf945fad68f3",
    "Estevan": "642672e0275fdf945fad68df",
    "Kindersley": "642672ff275fdf945fad68e1",
    "Melville": "64267314275fdf945fad68e3",
    "Moose Jaw": "6426731e275fdf945fad68e5",
    "North Battlefords": "64267329275fdf945fad68e7",
    "Prince Albert": "6426734a275fdf945fad68e9",
    "Assiniboia": "",
    "Broadview": "",
    "Carlyle": "",
    "Canora": "",
    "Esterhazy": "",
    "Indian Head": "",
    "Kamsack": "",
    "Leader": "",
    "Maple Creek": "",
    "Moosomin": "",
    "Outlook": "",
    "Rosetown": "",
    "Shaunavon": "",
    "Wadena": "",
    "Wakaw": "",
    "Wynyard": "",
    "Beauval": "",
    "Black Lake": "",
    "Buffalo Narrows": "",
    "Buffalo River Dene Nation": "",
    "Canoe Lake Cree First Nation": "",
    "Creighton": "",
    "Cumberland House": "",
    "Deschambault Lake": "",
    "Fond du Lac": "",
    "Hudson Bay": "",
    "Ile a la Crosse": "",
    "La Loche": "",
    "Montreal Lake Cree Nation": "",
    "Pelican Narrows": "",
    "Pinehouse": "",
    "Sandy Bay": "",
    "Southend": "",
    "St. Walburg": "",
    "Turnor Lake (Birch Narrows Dene Nation)": "",
    "Wollaston Lake": "",
    "Ahtahkakoop Cree Nation": "",
    "Beardy's and Okemasis Cree Nation": "",
    "Biggar": "",
    "Blaine Lake": "",
    "Carrot River": "",
    "Cut Knife": "",
    "English River First Nation": "",
    "Humboldt": "",
    "Loon Lake": "",
    "Nipawin": "",
    "Onion Lake Cree Nation": "",
    "Melfort": "",
    "Meadow Lake": "",
    "Lloydminster": "",
    "Pierceland": "",
    "Punnichy": "",
    "Rose Valley": "",
    "Rosthern": "",
    "Shellbrook": "",
    "Spiritwood": "",
    "Stanley Mission": "",
    "Unity": "",
    "Whitefish (Big River) First Nation": "",
    "La Ronge": "",
    "Fort Qu'Appelle": "",
};

export const skProvincialCourtOffices = {
    "Estevan": ["Carlyle", "Weyburn"],
    "La Ronge": ["Black Lake", "Creighton", "Cumberland House", "Deschambault Lake", "Fond du Lac", "Pinehouse", "Southend", "Stanley Mission", "Wollaston Lake"],
    "Lloydminster": ["Onion Lake Cree Nation", "St. Walburg"],
    "Melfort": ["Carrot River", "Hudson Bay", "Nipawin", "Wakaw"],
    "Meadow Lake": ["Beauval", "Turnor Lake (Birch Narrows Dene Nation)", "Buffalo Narrows", "Buffalo River Dene Nation", "Canoe Lake Cree First Nation", "English River First Nation", "Ile a la Crosse", "La Loche", "Loon Lake", "Pierceland"],
    "Moose Jaw": ["Assiniboia"],
    "North Battlefords": ["Biggar", "Cut Knife", "Spiritwood", "Unity"],
    "Prince Albert": ["Ahtahkakoop Cree Nation", "Montreal Lake Cree Nation", "Pelican Narrows", "Sandy Bay", "Shellbrook", "Whitefish (Big River) First Nation"],
    "Regina": ["Fort Qu’Appelle", "Indian Head"],
    "Swift Current": ["Leader", "Maple Creek", "Shaunavon"],
    "Saskatoon": ["Beardy’s and Okemasis’ Cree Nation", "Blaine Lake", "Humboldt", "Kindersley", "Outlook", "Rosetown", "Rosthern"],
    "Wynyard": ["Punnichy", "Rose Valley", "Wadena"],
    "Yorkton": ["Broadview", "Canora", "Esterhazy", "Kamsack", "Melville", "Moosomin"],
}